codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...100"
  status:
    project: yes
    patch: yes
    changes: no
  #notify:
  #  slack:
  #    default:
  #      url: https://hooks.slack.com/services/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
  #      threshold: 1%
  #      only_pulls: false
  #      branches: null
  #      flags: null
  #      paths: null
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - tests/**/*
  - routes/**/*
  - resources/**/*
  - database/**/*
  - public/**/*
  - app/templates/*
  - app/Http/Controllers/*
  - app/Models/*
  - config/**/*
